fsqrt:
	verilator -I../ -Wall -Wno-fatal --trace --cc --exe --build tb_fsqrt.cpp ../fsqrt.sv 
	./obj_dir/Vfsqrt
	
FMA:
	verilator -I../ -Wall -Wno-fatal --trace --cc --exe --build tb_fma.cpp ../FMA.sv 
	./obj_dir/VFMA
	
fln:
	verilator -I../ -Wall -Wno-fatal --trace --cc --exe --build tb_fln.cpp ../fln.sv 
	./obj_dir/Vfln
	
fadd:
	verilator -I../ -Wall -Wno-fatal --trace --cc --exe --build tb_fadd.cpp ../fadd.sv 
	./obj_dir/Vfadd
