fsqrt:
	verilator -I../ -Wall -Wno-fatal --trace --cc --exe --build tb_fsqrt.cpp ../fsqrt.sv 
	./obj_dir/Vfsqrt
	
FMA:
	verilator -I../ -Wall -Wno-fatal --trace --cc --exe --build tb_fma.cpp ../FMA.sv 
	./obj_dir/VFMA
